import libctg_HurricaneTrackDataset.__prototype__ as prototype
import libctg_HurricaneTrackDataset.ibtracs as ibtracs

from libctg_HurricaneTrackDataset.__prototype__ import *
from libctg_HurricaneTrackDataset.ibtracs import *